### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by LaggyAvocado** [jeremypelletier/novoline-unlicensed#13]
![image](https://user-images.githubusercontent.com/95762543/145270034-5c96b655-f9c9-45ae-bab1-7a1e122a0f99.png)

**Comment by rfl890** [comment]
run with -noverify in jvm args

**Comment by LaggyAvocado** [comment]
> run with -noverify in jvm args

That is with -noverify

**Comment by LaggyAvocado** [comment]
Do I have to remove the other arguments aswell?

**Comment by ImaginativeLAA** [comment]
no just put -noverify at the beginning

**Comment by jeremypelletier** [comment]
Read.
