### ISSUE TITLE
Gui drop down issue

### ISSUE THREAD

**Issue by minecrafthaxor** [jeremypelletier/novoline-unlicensed#14]
when ever i open the gui and press the drop down menu it dosent open

**Comment by iGreenyyyyy** [comment]
save a random config. open the config file. search for "click_gui". change mode from compact to dropdown.

**Comment by iGreenyyyyy** [comment]
then save the file and load the config in game

**Comment by jeremypelletier** [comment]
You have to drag open the bottom part if I remember correctly.
