### ISSUE TITLE
CRASH!!!!

### ISSUE THREAD

**Issue by SakurajimaMai02** [jeremypelletier/novoline-unlicensed#17]
After logging in , it CRASH!!
My launcher told me it’s cuz my graphics card is too old or bad(intel graphics 4600)
If it’s true? How2 solve it?(without purchase a new graphics card xd）

and plz update soon!

**Comment by SakurajimaMai02** [comment]
im using win10 64bits and i added -noverify

**Comment by jeremypelletier** [comment]
" My launcher told me it’s cuz my graphics card is too old or bad(intel graphics 4600)"
