### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by dremonq** [jeremypelletier/novoline-unlicensed#2]
Crashes when I press login

**Comment by jeremypelletier** [comment]
Enter any uid and make sure you run with noverify. If the problem still persists attach a crash report from the launcher.

**Comment by dremonq** [comment]
Still crashes even with -noverify even tho I entered the uid

**Comment by jeremypelletier** [comment]
You did not attach a crash report? I'm assuming it was resolved?
