### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [jeremypelletier/novoline-unlicensed#5]
Java args:
![image](https://user-images.githubusercontent.com/90822852/144548550-74b43bbd-08c7-4f0c-b69f-1e3f99bb029c.png)

Crash log:
https://pastebin.com/SBweBFDv

**Comment by jeremypelletier** [comment]
Sir there isn't even a crash shown in the report and you also cleared all your other arguments? Use default mc args with -noverify, disable attach mech is not needed.

**Comment by ghost** [comment]
Still crash with the default mc args

https://streamable.com/w692wi

**Comment by Zane2b2t** [comment]
Noverify at the start. not the end

**Comment by jeremypelletier** [comment]
> Still crash with the default mc args
> 
> https://streamable.com/w692wi

Novoline claims to not support windows 11 so that may be why possibly? I would assume the support would be because of the natives but considering the shader does not render on the main menu it could be your system regardless.

**Comment by ghost** [comment]
sure, maybe thats the reason.
