### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by ghost** [jeremypelletier/novoline-unlicensed#9]
The client crashes with -noverify at the start from what i hear this has been happening with a lot of other people too

**Comment by NathanW-05** [comment]
You're ratted 💀

**Comment by dremonq** [comment]
> You're retarded

**Comment by ghost** [comment]
> 

it anit

**Comment by 3000IQPlay** [comment]
> The client crashes with -noverify at the start from what i hear this has been happening with a lot of other people too
bruh it isnt crashing with -noverify

**Comment by 3000IQPlay** [comment]
Its not crashing with -noverify lol

**Comment by jeremypelletier** [comment]
> The client crashes with -noverify at the start from what i hear this has been happening with a lot of other people too

You are either doing it wrong, or you computer is not compatible with novoline. Please notice they only support 64 bit and NO WINDOWS 11

**Comment by ghost** [comment]
> The client crashes with -noverify at the start from what i hear this has been happening with a lot of other people too

you can try this https://www.youtube.com/watch?v=bu9GEUjU_XY&t=15s someone told me they tried it and it works apparently
